/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.bouncycastle.util.encoders.Base64;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

class SignerTest {
    @Test void signingHashMustMatch() throws IOException {
        // given
        Signer signer = new Signer();
        signer.setCert(new File("src/test/resources/certnkey2034.p12"));
        // when
        byte[] msg = "0045T23F606143CD076C0EE10000003914293ErCNC1120080104102302".getBytes(StandardCharsets.ISO_8859_1);
        byte[] signature = signer.sign(msg);
        // then
        byte[] expected = Base64.decode("MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAQAAMYICfDCCAngCAQEwVTBLMRYwFAYDVQQHDA1DSC00MDAyIEJhc2VsMQswCQYDVQQGEwJDSDENMAsGA1UECgwEREVNTzEVMBMGA1UEAwwMYXJjaGl2ZSBsaW5rAgYBibTdUmEwCQYFKw4DAhoFADANBgkqhkiG9w0BAQEFAASCAgBCrnwiLHZrgB45guW0eF4/kr3mHs7AJF4tich+SvfsFlJOp/bRqepk7Lj3mp6r9p1psGBk09NGW3Vp9xSn2kLwzzcIizl2/P+R+nW1c0sgyUHzG4vurbLzKZ6WrJspkd8kvaXD3iKL60sNP+6rw6FFxn/IxR6lsz9PFU06hjUljfUkpIiLT7cDkYWvglnVhs/GSpQzHkeTE1zdfrCNmPXCN5MmsT/ZoNeF2gu4dbfr9XxBefy7nJvZtw/G4K/Vb8ax5YOJZZPjfK3hXRtSxG0CZnzOsr7dh8+D3TXhGj0QICpzxXn2qLSZj25vhuBBFlJkj8TM3Bc37i3YEjOx5WdiWW/jSS/KW53WadI3SOpuICqYZGfu3SnWTDFdiC5GBoYVT9WDOQ+r+kXxqj3vZSdhbRhhH30rNj35t3AXa6vCzvZPRiRdEg2F6ifnRA5wsPxt+HeR7WeqMmzHRJkrnLCZ9opz0MO1/KdYJKJE4HbVclexG+L2Z66XPx4IrkH5wbTs4UG8mcuDf8/gXXjVs9WfQzcWvCPrF4hPox1D1L3lz9ufVyj3oGrF0JIDruZQ3SDT5GWDsbfRhJ9Ptr+ApptXxPEmPuvYGdqxXUeL9SaK9K3KHUY054iRtc0jCpADFMDUwkCvkPYpZjzzjsi4kw39kshvC9NGVsBL9yoj+GIt0AAAAAAAAA==");
        assertArrayEquals(expected, signature, "Hash does not match");
    }
}
